### ISSUE TITLE
ingestion process possibly not removing old mentions?

### ISSUE THREAD

**Issue by hexylena** [ElixirUK/TeSS#1029]
Hi TeSS team,

I recently deployed a very wrong if/else case to my json-ld which added incorrect `mentions` to my materials. E.g. https://tess.elixir-europe.org/materials/marine-omics-identifying-biosynthetic-gene-clusters the 'quarto notebook' is incorrect there.

Yesterday I merged a change that would remove that from the mentions but I notice it's still there. According to the logs the scraper ran this morning already so it should've been updated. Note that also there is an 'Associated Datasets' mentioned in TeSS which also isn't present in the ld+json:

```
  "mentions": [
    {
      "@type": "Thing",
      "url": "https://training.galaxyproject.org/training-material/topics/ecology/tutorials/marine_omics_bgc/workflows/",
      "name": "Associated Workflows"
    }
```

do I need to do something, or, would it be possible that TeSS syncs the mentions rather than simply adding to them?

**Comment by fbacall** [comment]
I think I can make TeSS remove redundant "external resources" if they are not present in an updated set of `mentions`, but if you wanted to entirely remove all external resources in an update, e.g. with:
```
"mentions": []
```
this would not be possible, due to how the JSON-LD gets parsed into RDF

**Comment by hexylena** [comment]
> I think I can make TeSS remove redundant "external resources" if they are not present in an updated set of mentions,

yes, I think that would be ideal, if there's any way that if the resources aren't mentioned, they're removed. (I should've been more careful in the first place with that if/else case but, I guess materials can also change over time, so, it's good if we can remove outdated/irrelevant resources)

> this would not be possible, due to how the JSON-LD gets parsed into RDF

Ah, that's ok, (in our case), we will make certain that there's at least one resource mentioned on every tutorial then

**Comment by fbacall** [comment]
Hmm, it should have been removed from the facets immediately. Thanks for flagging this, I'll have a look

**Comment by fbacall** [comment]
> [like this one](https://tess.elixir-europe.org/materials/qiime-2-cancer-microbiome-intervention)

This still has 1 external resource, which is because of the above issue about TeSS not being able to completely clear the list of external resources from an empty `mentions`.

What I could do is remove all external resources for GTN materials in TeSS, and then they will (hopefully) be rebuilt correctly the next time the scraper runs.

**Comment by hexylena** [comment]
oh, right, the empty mentions issue of course! I'm sorry, I forgot about that already. Hmm, I'll see if I can't find at least one useful thing to 'mention' for all of our training materials, and if not, I'll let you know and maybe then you can remove them mentions and we can re-create them?

**Comment by fbacall** [comment]
Sure, but it's really not a huge effort on my part to remove them... and possibly better than having some tenuous `mentions` on your materials :shrug:

**Comment by hexylena** [comment]
@fbacall ok, I could not find a useful mention. Yes, please remove them and let them be re-added. Thanks so much for being able to do that!
