### ISSUE TITLE
Setup SOLR server for testing

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#11]
As a lot of our code uses SOLR and travis CI has no SOLR support - create an outwardly accessible production SOLR server that can be connected to by Travis CI

**Comment by knirirr** [comment]
I've been looking at this one; it does seem to be a bit of a pain, particularly if filtering by IP address is ruled out. One alternative I saw suggested was this:

https://websolr.com/

But, the minimum cost would seem to be $50 per month and so that's probably out as well.

**Comment by njall** [comment]
Using an external server to test is considered a bad idea so will try and integrate this gem to mockup solr interactions - https://github.com/pivotal/sunspot_matchers

**Comment by anenadic** [comment]
Use cassette
