### ISSUE TITLE
More seed data (for nodes)

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#12]
We can potentially re-use the YML file about nodes in CKAN to create the nodes fixtures.
https://github.com/ElixirUK/TessScraperRuby/blob/master/nodes.yml

**Comment by anenadic** [comment]
The above yml file is now converted into json and should be used as a basis for the node model: https://github.com/ElixirUK/newtessscraper/blob/master/elixir_nodes.json

**Comment by fbacall** [comment]
Is there any reason to have it in JSON? Might be easier to parse if it was YAML.

Also I am going to move it into the TeSS repo.

**Comment by anenadic** [comment]
No particular reason not to be YAML.
