### ISSUE TITLE
/users route needs to be publicly accessible

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#131]
No need for users to be logged in to see the list of registered users.

**Comment by anenadic** [comment]
Do not display email address and authn token unless the user is the current user on /users/:id

**Comment by knirirr** [comment]
I don't think we should be showing the list of users to the public. In any case I would expect the number of users to be low with most material added automatically by scrapers.

**Comment by anenadic** [comment]
We leave this route protected then.
