### ISSUE TITLE
Sort out write access

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#139]
Write access (update/create methods) should be restricted to certain accounts. Write actions will be accessible by different accounts for different models. Below aims to describe how restrictions should be applied. UI is online forms (the submission of New and Edit pages from within a browser). API is JSON post/put 

|  | Event | Materials | Packages | Nodes | Workflows |
|---|---------|---------------|----------|-------------|--------------|
| UI | a | au | au | a | au |
| API | as | as | as | ? | - |

Key:

|abbr| role | 
|----| -------------------|
| a | admin | 
| u | regular_user | 
| s | api_user/scraper |

**Comment by njall** [comment]
So far applied to the Events controller.

**Comment by anenadic** [comment]
I have renamed the role 'harvester' -> 'api_user'
