### ISSUE TITLE
Get certificate for tess-old.elixir-uk.org from https://letsencrypt.org/

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#157]

**Comment by anenadic** [comment]
Lasts for 3 months only, needs script to automatically renew it. Also some issues reported with ngnix.

**Comment by knirirr** [comment]
We're using apache on tess-old so this would probably be OK. However, I have got a 1-year certificate from StartSSL which is adequate for the purpose of encrypting logins and deployed that.
