### ISSUE TITLE
Add a scraper for research IT training events

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#163]
http://www.ucl.ac.uk/isd/services/research-it/training

(James Hetherington from UCL)

**Comment by knirirr** [comment]
I'm having trouble with this one. Everything for a course should be in:

    <section class="content-box course-details-table">

...but I can't even pull that out. Any suggestions welcom.

**Comment by njall** [comment]
Possibly search for h3 elements with class heading that have an a element within to get name and url. Then follow URL to get more info
`<h3 class="heading">
<a href="http://development.rc.ucl.ac.uk/training/intro-to-shell/" target="_self">Introduction to the Unix Shell<br></a>
</h3>`

**Comment by knirirr** [comment]
This is still rather difficult as the content is pretty much unstructured.

**Comment by njall** [comment]
Moved to TeSS_Scrapers
