### ISSUE TITLE
Add more lines to description textarea for content providers/edit and fix font for 'add keyword' button

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#171]
![screen shot 2016-03-31 at 13 46 13](https://cloud.githubusercontent.com/assets/631719/14176067/02f8d324-f747-11e5-8da8-0f7bff977540.png)

**Comment by knirirr** [comment]
That description box appears to be draggable and so could be resized on the fly by the user, although I agree that making it bigger to start with would be a good idea.
