### ISSUE TITLE
Set up cron jobs for rerunning scrapers daily

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#174]

**Comment by anenadic** [comment]
We need to know which exact scrapers have been run initially to form the current DB and then need to rerun them and delete the old one not in use as not to confuse us.

**Comment by knirirr** [comment]
I think that the only suspect one is the Goblet one, and I get the impression that the latest one is the goblet_rdfa_scraper. I'm testing this now on the main site.

**Comment by knirirr** [comment]
It looks like this ran successfully through cron - please let me know if you seen anything dodgy.
N.B. I had to change the role of the scraper user so it might be necessary to fix the controller to allow the proper role to create/update.

**Comment by anenadic** [comment]
Hmm, not sure why the api_user does not work - I'll put a new issue in.

**Comment by njall** [comment]
cronjob details: 

00 4 * * *  /home/tess/TeSS/run_scrapers.sh /home/tess/scrapers/newtessscraper/ >> /tmp/tess_scraper.log
