### ISSUE TITLE
Support for entering lists for material:new

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#18]
Fields that allow lists are, for example: scientific topic, authors, contributors, target audience, etc.

**Comment by njall** [comment]
I've begun work on this. It's two different jobs really, the first of which I've completed.
1) Free text multiples like authors, contributors, and keywords
2) Controlled Vocab multiples like target audience, difficulty, and scientific topic. 

2 is dependant on implementing all the controlled vocabs e.g. #44
