### ISSUE TITLE
Add Markdown support for long description field in material/show page.

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#183]
Some descriptions scraped (e.g. from NGS registry) contain Markdown syntax. Add support to rende them nicely on material/show page.

**Comment by knirirr** [comment]
Not all TeSS records have markdown in, so we would have to either specify in the controller which ones did (probably a bad idea) or attempt to detect markdown when rendering strings on the page. This could be difficult as it would probably involve regexes.

The other possibility would be to modify the scrapers to convert known markdown - I just tried this for the NGS scraper and it certainly looks nicer.
