### ISSUE TITLE
Adding events or content providers manually does not seem to index them in Solr

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#187]

**Comment by knirirr** [comment]
I tried this now on my local installation and was able to find the newly-added record immediately via a search. This would seem to fit with the description here of indexing being tied in to the save callbacks (see Reindexing Objects):

https://github.com/sunspot/sunspot

If it's not working elsewhere then perhaps this may be of use?

https://stackoverflow.com/questions/3632278/sunspot-rails-not-re-indexing-model-after-save

**Comment by anenadic** [comment]
This needs checking - I've been having this issue for ages but could be something on my machine. Should try on TeSS production, too.

**Comment by fbacall** [comment]
I have the same problem

**Comment by fbacall** [comment]
and now its working fine... strange
