### ISSUE TITLE
Set the min width on the body or main container to be that of iphone or similar

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#193]
So that it cannot be minimised past a certain point.

**Comment by anenadic** [comment]
Pages need adjusting at the min-width of 320px - things overflow to the right. Sidebar or other stuff possibly needs hiding.

![screen shot 2016-05-24 at 14 31 40](https://cloud.githubusercontent.com/assets/631719/15506070/01f68a7e-21be-11e6-923e-e1469313310e.png)
![screen shot 2016-05-24 at 14 31 40](https://cloud.githubusercontent.com/assets/631719/15506072/03aee564-21be-11e6-8c19-c6e688e19ba9.png)

**Comment by fbacall** [comment]
Fixed by #210
