### ISSUE TITLE
Scraper/feed for ErasysApp training resources

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#201]
http://www.sbedu.eu/
An RSS feed: http://www.sbedu.eu/index.php?format=feed&type=rss

**Comment by njall** [comment]
From duplicated issue:

Some great training materials here http://www.sbedu.eu/

Thanksfully they have an RSS feed:
http://www.sbedu.eu/index.php?format=feed&type=rss

It only shows 5 at a time so you need to add &start=5 &start=10 &start=15 to the URL to load all pages until you run out. e.g. e.g. http://www.sbedu.eu/index.php?format=feed&type=rss&start=10

It currently goes up to 31 materials; but it would be best (more dynamic) to keep incrementing the &start parameter until the page returned is equal to this page: http://www.sbedu.eu/index.php?format=feed&type=rss&start=99999999

**Comment by knirirr** [comment]
I've been looking at this; the RSS is easy to scrape but then one must get the tags from the individual page for each record. This sort of works so far.

**Comment by knirirr** [comment]
Other than that I can't see how to find a description (looks like it's in unadorned <p> tags) it seems to work.

**Comment by njall** [comment]
Hmmm, looks like they have RDFa schema.org stuff embedded. Let me just see if I can parse it with the parser I used for the Belgian nodes stuff

**Comment by njall** [comment]
This is what information is stored in it with RDFa 

http://linter.structured-data.org/?url=http:%2F%2Fwww.sbedu.eu%2F

**Comment by knirirr** [comment]
Thanks. It would be useful if the Belgian RDF stuff could be repurposed. I note that RSS parsing was very easy (particularly easy to detect the end of the feed) but it's not much good if they don't put much information there.

**Comment by njall** [comment]
I'm taking a look now. It does parse most of it; but its struggling with a couple of fields. Given we'll be using this RDFa parser quite a lot more (hopefully) I'll work on improving it to handle this

**Comment by njall** [comment]
Blergh. I fixed up the RDFa parser for it but the contents are not great. We have:
**RSS** - title, link, description, author
**RDFa index** - title, link, author, keywords
**HTML Scraping each page** - title, link, description, author, keywords

I think I'll just do RDFa and then try and pull out the description from the HTML

**Comment by njall** [comment]
Completed: https://tess.elixir-uk.org/content_providers/erasys-app
