### ISSUE TITLE
Erasys App Content Feed

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#202]
Some great training materials here http://www.sbedu.eu/

Thanksfully they have an RSS feed:
http://www.sbedu.eu/index.php?format=feed&type=rss

It only shows 5 at a time so you need to add &start=5 &start=10 &start=15  to the URL to load all pages until you run out. e.g. e.g. http://www.sbedu.eu/index.php?format=feed&type=rss&start=10

It currently goes up to 31 materials; but it would be best (more dynamic) to keep incrementing the &start parameter until the page returned is equal to this page: http://www.sbedu.eu/index.php?format=feed&type=rss&start=99999999

**Comment by anenadic** [comment]
Duplicates #201
