### ISSUE TITLE
Add Clinical Bioinformatics training from Andy Brass/FutureLearn

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#205]
https://www.futurelearn.com/courses/bioinformatics

Possibly easier to add it manually.

**Comment by njall** [comment]
Done. Added a scraper for Futurelearn that takes adds the [Genomics Collection](https://www.futurelearn.com/courses/collections/genomics) and the [search results for Bioinformatics](https://www.futurelearn.com/search?utf8=%E2%9C%93&q=Bioinformatics)

https://tess.elixir-uk.org/events/clinical-bioinformatics-unlocking-genomics-in-healthcare
