### ISSUE TITLE
Boostrap columns issue on small devices

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#207]
Boostrap columns are not proportional: left-hand column of size 3 looks bigger than main container of size 9.

There is a lot of white space around the main container not used - we need to adjust the site's width. Also need to set the minimum width so that the page cannot be minimised past a certain point (issue #193).

![screen shot 2016-05-11 at 13 27 20](https://cloud.githubusercontent.com/assets/631719/15180905/2b930426-177c-11e6-91db-8ad5fb3bfe24.png)

**Comment by fbacall** [comment]
What about this:

Normal on medium & large screens:
![screen shot 2016-05-25 at 17 21 58](https://cloud.githubusercontent.com/assets/503373/15547809/5f730be8-229d-11e6-9ba7-a0a1775d6065.png)

Sidebar disappears on small screens and filter button appears:
![screen shot 2016-05-25 at 17 22 25](https://cloud.githubusercontent.com/assets/503373/15547813/62f55af0-229d-11e6-8dd0-7bf6be184299.png)

Sidebar pops up when filter button clicked:
![screen shot 2016-05-25 at 17 22 28](https://cloud.githubusercontent.com/assets/503373/15547815/651cf39c-229d-11e6-8301-5eefb4598ca7.png)

**Comment by anenadic** [comment]
Let's clone Finn
