### ISSUE TITLE
Annotate our resources with schema.org

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#215]
We often encourage other people to use schema.org types to annotate their materials. We should practice what we preach and markup events and materials with schema.org types 'events' and 'creativeworks'

**Comment by knirirr** [comment]
For materials, here's how various fields are currently written:

                    <p><b><%= model_class.human_attribute_name(:licence) %>: </b><%= (@material.licence.blank? or @material.licence == 'notspecified') ? empty_tag(:span, 'none specified') : licence_name_for_abbreviation(@material.licence) %></p>

Here's one way of marking up the authors field without using `raw`, `html_safe`, or the like:

    <p>
                  <b><%= model_class.human_attribute_name(:authors) %>: </b>
                  <% if @material.authors.blank? -%>
                    <% empty_tag(:span, 'none specified') -%>
                  <% else -%>
                      <% @material.authors.each do |auth| -%>
                        <span itemprop='author' itemscope itemtype='https://schema.org/Person'><%= auth -%></span><% unless auth == @material.authors.last -%>,<% end -%>
                      <% end -%>
                  <% end -%>
                </p>

But, is this too unpleasant? I can alter the other fields to look like this but I thought it better to ask first in case anyone has a neater looking idea.

**Comment by knirirr** [comment]
@njall suggested this instead:

    <%= content_tag(:span, auth, {:itemprop => 'author', :itemtype => 'https://schema.org/Person'})  -%><% unless auth == @material.authors.last -%>,<% end -%>

**Comment by knirirr** [comment]
I can't think of anything else to add and so I'll close this.
