### ISSUE TITLE
Add support for auto-filling keywords, scientific topics and audience on materials based on previous inputs or dictionaries

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#22]

**Comment by anenadic** [comment]
Something like BioSharing already does.

**Comment by knirirr** [comment]
I recently added autocomplete to a text field on BioSharing. For an example of this try the "scope and data types" search box here:

https://biosharing.org/advanced-search/?search_state=visible

This should be quite easy to add using the javascript I've deployed here combined with an API to provide the list. But, where should it go? Is it for searching or should it be somewhere else? If for searching I could autocomplete with all keywords and existing training material titles.

**Comment by knirirr** [comment]
This has now been implemented for the materials edit form.
