### ISSUE TITLE
'Add to my calendar' button on Events

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#225]
Use the Google calendar API https://developers.google.com/google-apps/calendar/overview (or another than can use iCal too) to save an event to your calendar. This can be on the events show page

**Comment by knirirr** [comment]
What I've just added only downloads an ical file, but that can be imported in to Apple or Google calendars.
To go the full API route we need to register TeSS under someone's Google account; it does seem a bit involved simply to post an update to Google Calendar.

**Comment by anenadic** [comment]
Download an ical file should be sufficient - closing this issue.
