### ISSUE TITLE
Modules/classes in lib/ should be automatically loaded

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#231]

**Comment by anenadic** [comment]
Probably a naming issue - module name should be 'Tess' and not 'TeSS'

**Comment by fbacall** [comment]
I think `config.autoload_paths` doesn't automatically load the given paths when the application boots.

Instead, if you call `Tess::Something` and "lib" is given as an autoload_path, Rails will look in lib/tess/something.rb

If we want to have something automatically loaded on application boot, it needs to be required in an initializer. See: https://github.com/seek4science/seek/blob/master/config/initializers/seek_main.rb
