### ISSUE TITLE
Remove sidebar on new/edit forms

### ISSUE THREAD

**Issue by fbacall** [ElixirUK/TeSS#234]
Can put the info block somewhere else. Or remove it.

#207

**Comment by anenadic** [comment]
Not sure about this - we keep getting asked the same questions about resources in TeSS over and over again so these info boxes clearly state what it is that people are adding to TeSS.

**Comment by fbacall** [comment]
This is what I had in mind:
Medium & large:
![screen shot 2016-05-26 at 17 10 55](https://cloud.githubusercontent.com/assets/503373/15581604/e8747126-2364-11e6-8e65-3f37b421a333.png)

Small:
![screen shot 2016-05-26 at 17 10 48](https://cloud.githubusercontent.com/assets/503373/15581606/eab0b242-2364-11e6-8287-0a67fd7674f1.png)

**Comment by anenadic** [comment]
Love it. Need the same for content providers, packages and workflows.

**Comment by anenadic** [comment]
I'd also like them to be more prominent on index pages, but not too sure how to achieve this - info buttons are too hidden and not too sure about sidebar either.

**Comment by fbacall** [comment]
What if the info buttons said "What is x?" on them, instead of just having the "info" symbol?

**Comment by anenadic** [comment]
I actually that exact thing yesterday - added the text to the info buttons.
