### ISSUE TITLE
Convert all old scrapers to use the new TeSS' API

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#25]
Convert all old scrapers to use the new TeSS' API. Then import the data into TeSS.

**Comment by knirirr** [comment]
Shouldn't it be me doing this one?

**Comment by njall** [comment]
I think that'd be more sensible, yes

**Comment by knirirr** [comment]
Goblet scraper done.

**Comment by knirirr** [comment]
A couple of others added, but there seems to be a problem with adding keywords and scientific topics. Have either of you mangaed to add those to a record yet?

**Comment by njall** [comment]
Yes, they're of an array type. There's 3 examples of them being written directly through activerecord in db/seeds.yml - not sure exactly how this will translate to JSON. Hopefully just:
 keywords: [blah, blah, blah]

**Comment by knirirr** [comment]
SIB, genome3d and EBI done.

**Comment by knirirr** [comment]
All the old ones have been converted and Goblet now uses the API.
