### ISSUE TITLE
Create new scrapers for content providers not currently in TeSS

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#26]
Lists of content providers (nodes get priority):
http://dev.mygrid.org.uk/wiki/display/EL/TeSS+Content+Providers

https://docs.google.com/spreadsheets/d/12A09OtXXJo3V3oo68NpmV2mlbk4h_wlC0Ym-IDyRQlE/edit

**Comment by njall** [comment]
As this doesn't require a scraper I've added them as records in the db/seeds.yml file
