### ISSUE TITLE
scraper user not authorized on tess.elixir-uk.org

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#262]
Currently having to use an admin account! 
Account tess@elixir-uk.info is not working

**Comment by knirirr** [comment]
It could be the material_policy.rb file - there was an 'and' rather than an 'or':

          if @user.has_role?(:api_user) or @user.is_owner?(@record) # check ownership

That seems to be OK for me - is it working for you?

**Comment by knirirr** [comment]
The problem described above was affecting content providers but not events. Anyway, I think this works so I'll close the ticket.
