### ISSUE TITLE
BITSVIB content provider keeps vanishing!

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#265]
I was messaged by the Belgian people that their content isn't on TeSS. I reran the scraper to get it back on and they thanked me. 
I looked again today and it's vanished again from the content providers page and as a filter on the materials page; however searching for BITS retrieves their materials with 'Provider not available' listed as content provider:
https://tess.elixir-uk.org/materials/introductory-statistics-in-graphpad-prism

This needs investigating

**Comment by knirirr** [comment]
When did you last re-run the scraper?

I can only think that there's something wrong with the scraper cron job which is clobbering the content provider record for BITS; a quick look at the tess account shows that they've not been updated to the latest versions, which could well be it.

I've temporarily disabled the cron job as I'm in the middle of another task right now, but I will update the scraper script and repository as soon as I have a moment. Meanwhile, if you run the bitsvib scraper again it should restore the provider.

**Comment by njall** [comment]
The Khan Academy ones were in a similar state - being unlinked from their content provider.

**Comment by knirirr** [comment]
The clobbering has been fixed by my last commit, and this ticket may therefore be closed when the scrapers are updated on the production server.

**Comment by anenadic** [comment]
This is because we only show providers with >0 materials or events. I have fixed this now.

**Comment by anenadic** [comment]
The vanishing happened when we re-run scrapers, which failed to add any materials or events and they were not displayed we we had the logic to show only those with > 0 resources. See also issue #276.

**Comment by anenadic** [comment]
We need to update all RDF-a-based scrapers do to the changes in RDFa gem and then make sure they all run correctly - issue #277. Then we can close this issue.
