### ISSUE TITLE
All RDFa-type scrapers need updating to be in line with the latest schema annotations #2

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#277]
See https://github.com/ElixirUK/TeSS_scrapers/issues/2

**Comment by anenadic** [comment]
All scrapers need testing to make sure they run correctly. We should 'retire' the unused scrapers into a separate folder perhaps.

**Comment by njall** [comment]
@knirirr has updated them and I've patched a few things up and tested. Closing for now as everything appears to be working.

**Comment by njall** [comment]
FYI, you'll need to update to Ruby 2.2.2 when you next pull as it's needed for one of the latest dependencies, active support
