### ISSUE TITLE
External Resource Text Field for Materials

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#280]
Create a new table that stores associations between Materials and external resources. Currently it simply needs to store the source object and the URL as a string e.g. <#Material> - 'http://biosharing.com/1'
This may get extended to storing more metadata about the external resource such as it's name, description, and logo of the resource. Eventually when our partners get their APIs sorted we will be able to automatically pull this info in, but we should always store the backup just incase their APIs go down.
The most simple level to be finished by July 29th.

**Comment by knirirr** [comment]
How would you plan to get the correct id from biosharing to store in this field? It will be something like biodbcore-000001 (databases) or bsg-[s/c/p]000001 (everything else).

**Comment by njall** [comment]
At the moment it will just be the whole URL copied and pasted in by the user e.g. https://biosharing.org/bsg-s000004 or https://biosharing.org/biodbcore-000001 or https://bio.tools/tool/free.fr/OntoBrowser/1 - They'd just find it on BioSharing and paste it in. The next stage will be to have a queryable widget of BioSharing records that fills in the URL text box; but we don't have to worry about that for now

**Comment by anenadic** [comment]
Also for events.
