### ISSUE TITLE
Display 'newest materials' on home screen

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#284]
To keep the site looking live we could have on the homepage a 'latest materials' section. Find materials within 'created date' within the previous month. Display as 'latest from _content provider_'

**Comment by knirirr** [comment]
Are you thinking of a large display of the latest from every content provider, or something like the top 5/10 newest, with the provider displayed for each?

If the latter then it could be done with a similar layout to the elements above and would therefore be quite compact.

**Comment by njall** [comment]
I think the latter in the space beneath the photo links to different pages.

I've restored the sort_by 'new' option so we could add 'see more' underneath the newest materials that links to https://tess.elixir-uk.org/materials?sort=new

**Comment by knirirr** [comment]
I've checked in a branch to show you what I meant by that suggestion - if this is any good I could merge.

**Comment by knirirr** [comment]
I've modified this as per the comments on Skype and merged it.
