### ISSUE TITLE
Issue with confirmation e-mail after registration

### ISSUE THREAD

**Issue by agbeltran** [ElixirUK/TeSS#291]
After registering in the site:

https://tess.elixir-uk.org/

I received an e-mail to confirm my registration where localhost is used instead of the tess.elixir-uk.org site:

http://localhost/users/confirmation?confirmation_token=<token>

**Comment by fbacall** [comment]
Hi, thanks for reporting this.

I have a put a temporary fix in place, so it should be OK now, but we will need to look into how to stop it happening again.

**Comment by fbacall** [comment]
Fixed by 10ddd7a25f546a078ff3d8b6e333ad887d3a84bd
