### ISSUE TITLE
On saving workflows - detect links to internal resources in workflow nodes' decriptions and turn them into internal links

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#298]
Detect when a link points to a resource internal to TeSS and make appropriate changes so if we ever change the TeSS DN at least those links don't break.

**Comment by fbacall** [comment]
This could probably by done in the Javascript.

The browser knows the URL of the current page, and so could recognize that the resource being linked to is on the same domain. Then it could strip the URL down to its relative form e.g. `/materials/123` and store that on the node.
