### ISSUE TITLE
Allow users to create profile page

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#31]
Allow users to create a Profile record that belongs_to their User account.

**Comment by anenadic** [comment]
At the time of registering, people should be allowed/required? to create profile.

**Comment by knirirr** [comment]
This has been added starting with commit 6bb171a6fda9cc2034debe6f1d80c72738e08d3d . The profile is created automatically on registering but only has the email address (which will try to get an image via Gravatar). Users may edit this to add their full name and website.

I've also changed things such as only admins may do a full edit of a user model, for that includes all manner of things which users don't need to be dealing with. There's a password reset/close account button on the profile page.
