### ISSUE TITLE
New Events metadata

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#332]
The events metadata needs to be brought inline with the bioschemas.org model. That is; everything with an M, and R, or an O in the CG field of this table:
https://docs.google.com/document/d/12O8gsOuH2qHKpis6vTHxXExraNH5XZEnoilwNgWWgaQ/edit#heading=h.uc6mc8iukqe

**Comment by njall** [comment]
Some things will change when we work on the spec more so for now:

* Rename 
   Categories --> Event Type
   Fields --> Scientific Topic (And start using the ontology like in Materials)
   Event Host --> Organizer
* New fields:
  Contact
  Target Audience
  Capacity
  Eligibility
  
 * The only thing that should become mandatory is location (city and country fields) - unless 'online' is selected. So this won't be a database constriction.  

* Online and For profit can be left in as is

**Comment by fbacall** [comment]
When migrating Event "fields" to scientific topics, what should we do with fields that don't match any terms from the scientific topic ontology? Just discard them?

**Comment by njall** [comment]
I think we need to write a mapper. I'll start one ask Rafa to finish the sciencey bits I don't understand

**Comment by njall** [comment]
https://docs.google.com/spreadsheets/d/1Wly-wLQZbWQ-bj_lbbvpXIF_ijAtoEr4Y9ymXQLxE44/edit#gid=0

**Comment by njall** [comment]
I'm just waiting on some scientists to sort out the ones where there's no obvious mapping

**Comment by njall** [comment]
Event Type: 
Awards and prizegivings
Meetings and conferences
Receptions and Networking
Workshops and courses

Migrate all 'course' to 'Workshops and courses'
Migrate all 'meetings' to 'Meetings and conferences'
Ignore 'event' as everything is an event

Add host institution

**Comment by fbacall** [comment]
What if the host is not a university? Could be at a hotel, for example

**Comment by njall** [comment]
I think host is the university looking after everything; and venue is the place. Like the RSE conference was hosted by Manchester but the venue was the MOSI.

**Comment by njall** [comment]
I think the hotel would be the location and an institution would be the
host I think. Like University of Manchester hosted the RSE conference but
the location was the MOSI.

Niall Beard
