### ISSUE TITLE
Issue with resources with the same name as a previous resource

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#340]
A resource from DTLS wasn't added to TeSS despite all the others being added correctly.

I found that there was a resource with the same name that ran several months earlier here: https://tess.elixir-uk.org/events/python-for-life-scientists
For some reason that old event didn't get updated to the new one. I believe it should create a new event if the URL is different. At the moment 'check_exists' falls back to title

**Comment by knirirr** [comment]
check_exists has been updated to remove title (#357).
