### ISSUE TITLE
Material/Event Sorting needs looking into

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#344]
Doesn't seem to sort correctly alphabetically

**Comment by fbacall** [comment]
It seems to be sorting by character code, e.g. `ABC ... XYZabc ...` so lowercase letters always appear after uppercase.

**Comment by fbacall** [comment]
I think the only way to fix it is by either converting the title field to lowercase when indexing, or adding a second "title" field in lowercase that is solely used for sorting.

**Comment by knirirr** [comment]
Is this still a problem? I'm seeing case-insensitive sorting on my local installation.

**Comment by fbacall** [comment]
It still is for me.

Has anyone done anything relating to this issue?

If not I will implement the `sort_title` solution described in the Sunspot README

**Comment by knirirr** [comment]
I've not done anything; I was planning to but I couldn't reproduce it locally.
