### ISSUE TITLE
Submit New event to iAnn

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#35]
Investigate whether we can submit new events registered in TeSS directly to iAnns registration form e.g. http://iann.pro/report-event
Submission can be opt-in with a checkbox on the TeSS Event form that says 'also submit to iAnn'.

**Comment by anenadic** [comment]
New event button should just open a new tab and take user to iAnn.

**Comment by knirirr** [comment]
@anenadic's suggestion is certainly very easy:


          <%= link_to new_event_path, :class=>"btn btn-primary" do %>
              <i class="fa fa-plus-square"></i> Register event
          <% end %>

...can be replaced with:

          <a href="http://iann.pro/report-event" target="_blank" class="btn btn-primary">
            <i class="fa fa-plus-square"></i> Register event
          </a>

In show.html for events. Is this what's actually required? I can commit it if so.

**Comment by njall** [comment]
I think we're scrapping that plan. Rather than pushing people into registering with iAnn we were just going to allow people to submit their own events into TeSS and then come up with a sync policy with iAnn later.

**Comment by knirirr** [comment]
OK, no problem. Unless we want to try guessing their captcha then we'll need some form of access granting from their end.
