### ISSUE TITLE
Add biosharing associations

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#350]
You can either do this as a rake script or add it to a new directory in the scrapers and use the API. Whichever one you feel most comfortable with.
The script should parse the CSV, find the correct material and add as an external resource

**Comment by knirirr** [comment]
I've now added this and can run `rake biosharing:create_links` whenever you're ready. Obviously an API would be better than my csv file for this purpose but there are still reasons why we're not able to proceed with one immediately, for which I apologise.

**Comment by knirirr** [comment]
Deployed.
