### ISSUE TITLE
Update check exists method

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#357]
Check exists causes error if something is named the same. At the moment it goes, 
Find by url -> no match? -> Find by title 

Find by title is not useful as things may be named the same (e.g. every software carpentry workshop, or recurring events). Probably best to just remove that bit

**Comment by knirirr** [comment]
I've removed this from the three controllers and related tests. IIRC the api gem simply posts the whole object and so it shouldn't need to be changed.
