### ISSUE TITLE
Add tooltip to events tiles

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#359]
When you hover over an event tile in the events index page it should have a tooltip that says what each of the icons mean e.g. this event is online and has already started

**Comment by knirirr** [comment]
It looks like these are already added, but they're not showing up for me. How about you?

If no-one can see them it probably means loading the necessary jquery-tooltip code and running `$('[data-toggle="tooltip"]').tooltip();` on document load.

**Comment by fbacall** [comment]
I can't see them either

**Comment by knirirr** [comment]
I have had to give up for now and ask if anyone has any ideas:

http://stackoverflow.com/questions/40286406/masonry-brick-media-item-blocks-tooltips

**Comment by knirirr** [comment]
I had another few minutes yesterday evening to glance at this. It seems that the masonry box is intercepting the mouseover events, so I've added a branch where I've applied to the tooltips to the box instead. It's not great but it may suffice until someone has a better idea as to how to get the correct elements to respond to the mouse.
