### ISSUE TITLE
Re-implement GOBLET scraper to utilize GOBLET API 

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#36]
GOBLET have implemented a content dump here:
 http://www.mygoblet.org/training-portal/materials-xml

It includes extra fields such as topics and will be more robust that the scraper.

**Comment by knirirr** [comment]
Interesting. When did they do that?

**Comment by njall** [comment]
In August, about a year after they opened the ticket. http://www.mygoblet.org/content/web-service-export-content-xml-andor-json
We haven't really gone over it yet but Carlos is still working for GOBLET (I believe) so we can give him any feedback further requests

**Comment by knirirr** [comment]
Sorry, that ticket was taking so long that I completely forgot about it. I'll take a look at it once I've sorted out what's mentioned in #25 (keywords &c).

**Comment by knirirr** [comment]
I'll work on this next.

**Comment by knirirr** [comment]
I've added a first draft of a scraper which parses the goblet API using nokogiri. It will probably need tweaking (e.g. we don't use the ratings which Goblet provides and may want to later, and may want to differentiate between materials and courses) but it does at least work.
