### ISSUE TITLE
Subscribe to Calendar

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#379]
On the events index page have a _subscribe to this filter_ button.

Appears when minimum of 1 filter is applied 

When the user clicks _subscribe_ it takes you to a page in TeSS that has

- The URL of the .ICS they need to import
- A description of how to add a new calendar in Google Calendars and a description of how to subscribe to iCal calendars (see import ical from internet) http://www.howtogeek.com/howto/30834/add-an-ical-or-.ics-calendar-to-google-calendar/

Ideally the URL of the ICS will be in the same form as the API e.g. tess.elixir-uk.org/events.ics?country=netherlands&topic=Bioinformatics 
When you go to this page it will generate and give to the user an ics file such as tess_events_netherlands_bioinformatics.ics

**Comment by fbacall** [comment]
So I did a test with google calendar.

I added the ICS link of an event (https://tess.oerc.ox.ac.uk/events/finn-is-testing-google-calendar-sync.ics) to google calendar, then edited the event to change the date and title.

It has been over 24 hours now and the event details in Google calendar haven't changed, so I don't think it polls for changes.

**Comment by fbacall** [comment]
Disregard the previous comment, it has updated now!

**Comment by njall** [comment]
Is it just quite slow to update then?
