### ISSUE TITLE
Filtering behaviour may need tweaking

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#390]
When filters are selected they do an OR (conjoin) on alike facets and an AND (intersection) on different facet types. Given it's doing an AND it should reduce the options in remaining filters  based on what will still give a result. 

So for example
https://tess.elixir-europe.org/events?country=Germany&event_types=Workshops+and+courses&scientific_topics=Bioinformatics

Has 1 result, which means all other filters that aren't associated  attributes of that one event should be hidden from view.

**Comment by fbacall** [comment]
For future reference: https://github.com/sunspot/sunspot/wiki/Working-with-search#working-with-facets
