### ISSUE TITLE
Scientific topics annotation

### ISSUE THREAD

**Issue by knirirr** [ElixirUK/TeSS#403]
Many, if not most, entries lack scientific topics. We could attempt to get these by sending a material's description to http://bioportal.bioontology.org/annotator and getting all the hits for EDAM topics.

There's a risk of false positives so we ought to review these. However, we don't have the time for much detailed curation, and so would benefit from a curation dashboard that would summarise all the pending additions of tags and allow admins to do a bulk approve/reject of them. Then, each time a material was created without scientific topics the Rails application could post to the web service and flag any hits on the curation dashboard.

As a first step a rake script that would test all the existing materials (perhaps rate-limited) and list them  and their hits in a csv file would be a test of whether this process might work.

**Comment by knirirr** [comment]
Commit 5e37d5364d8b341bbe0d2685e897902cea5d495c adds Sidekiq to a new branch, which will need `bundle install`, a migration, installation of Redis, and looking at these notes: http://railscasts.com/episodes/366-sidekiq

This _should_ create a new EditSuggestion linking a Material to one or more ScientificTopics, based on the result of a BioPortal search.

**Comment by knirirr** [comment]
A rake task needs to be created to add suggestions to existing topics via the above mechanism.

**Comment by njall** [comment]
This needs to be extended to include other resources like Events + Workflows. This might eventually be used for users too - so it's important to change the edit_suggestion model/process to be polymorphic.

**Comment by knirirr** [comment]
This should now be working - I've cleaned up some of the code as well.
I'm not sure on the effect of merging this in on any existing EditSuggestions, though.
