### ISSUE TITLE
Elixir AAI

### ISSUE THREAD

**Issue by knirirr** [ElixirUK/TeSS#412]
We need, it seems, to allow users to log in using Elixir's OpenID provider. Some documentation relating to this is here:

https://www.elixir-europe.org/services/compute/aai

...which points to this document:

https://docs.google.com/document/d/1vOyW4dLVozy7oQvINYxHheVaLvwNsvvghbiKTLg7RbY/edit

As we have Devise it would seem necessary to use an OpenID plugin for Omniauth, which would seem to indicate the following documentation:

https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
https://github.com/intridea/omniauth-openid

This might also be a possibility:

https://github.com/jjbohn/omniauth-openid-connect

**Comment by knirirr** [comment]
The latest commit allowed me to successfully log in to my local TeSS installation after authenticating with Elixir.

BUT - I had to disable verification of the Elixir token by editing two files:

    $GEM_HOME/gems/openid_connect-0.9.2/lib/openid_connect/response_object/id_token.rb 

...added `return` to line 22.

    $GEM_HOME/gems/json-jwt-1.7.0/lib/json/jws.rb

...added `return` to line 25.

Clearly this will not do at all for production use. I will attempt to find the source of the problem but would greatly appreciate any assistance if anyone can offer any.

**Comment by fbacall** [comment]
I was able to login without issue once, but the second time I got the verification problem.

**Comment by fbacall** [comment]
I think the AAI people have to manually approve your client to be able to recieve credentials.

**Comment by knirirr** [comment]
I've been using the development client, though. This should work without registration as long as one's running the client on  localhost:8080. When you logged in the first time were you using the hacks to the gems I mentioned above?

I was waiting until I had the code working but we could always register TeSS anyway, I suppose.

**Comment by fbacall** [comment]
No I was mistaken, it redirected to localhost:8080 (which wasn't the port I was running on) which I assumed meant it was "working", but now I understand the error happens after redirection.

The problem seems to be that the "id_token" is missing, which I understand can happen if you don't request the right scopes. But it seems you have to be "approved" by the AAI people before you are allowed to request such scopes. This happens with both the development client info and the one I registered.

**Comment by knirirr** [comment]
I'm not sure whether it's that - I asked them about registration and they seemed to indicate that it didn't matter when I was using the development client. If you've registered it and there's still a problem then it might not be that.

I was able to get an id_token by something like `raise omniauth.env` in the callbacks controller; checking this against the Elixir public key showed that the token is valid. What I think's happening is that the public key isn't making its way through the various method calls and so the id_token is not validated due to this missing key. There seems to be a missing nonce as well.

Setting `discovery: true` in the relevant section of the devise initialiser doesn't work either as the library detects an Oauth2 rather than an OpenID endpoint and fails by other means.

**Comment by fbacall** [comment]
Yeah you're right, I was mistaken. I tested the dev client just using curl and the id_token is there.

**Comment by fbacall** [comment]
OK I got it to verify the token, but there is still a problem with the nonce

**Comment by fbacall** [comment]
Right, it works if I disabled the "send_nonce" option, but you will have to clear TeSS' sessions, or delete your cookie (otherwise it will try and compare against a previously stored nonce)
