### ISSUE TITLE
Add legalese mumbo jumbo

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#419]
As our service agreement with GEANT we must provide to the End User, at least at first contact, in an easily, directly and permanently accessible way a Privacy Policy, containing at least the following information:

62 a. the name, address and jurisdiction of the Service Provider;
63 b. the purpose or purposes of the processing of the Attributes;
64 c. a description of the Attributes being processed;
65 d. the third party recipients or categories of third party recipient to whom the Attributes might be
66 disclosed, and proposed transfers of Attributes to countries outside of the European Economic
67 Area;
68 e. the existence of the rights to access, rectify and delete the Attributes held about the End User;
69 f. the retention period of the Attributes;
70 g. a reference to this Code of Conduct;

**Comment by njall** [comment]
https://wiki.refeds.org/display/CODE/Code+of+Conduct+for+Service+Providers

**Comment by fbacall** [comment]
For reference:
https://www.elixir-europe.org/legal/terms-of-use
https://www.elixir-europe.org/legal/privacy
