### ISSUE TITLE
Country name matcher

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#423]
People/scrapers are inputting different names for the same countries. e.g.
United Kingdom, UK, Great Britain, GB
Netherlands, Nederlands
TW, Taiwan

See if there are any existing, and if not - make one, synonym mapper for country names ran on save

**Comment by knirirr** [comment]
We dealt with this in BioSharing by using a controlled vocabulary for countries with a source from here:

https://restcountries.eu/rest/v1/all

I used a javascript autocomplete to access that source. Would it be worth doing the same here?

**Comment by njall** [comment]
Looks like a great resource. Can't be in autocomplete though as these are coming from scrapers chiefly. It'll have to be a before_save action on country fields.

**Comment by knirirr** [comment]
AFAIK this seems to be working properly so I'll close this.
