### ISSUE TITLE
Add Tool Type to bio.tools integration info

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#426]
On adding of tools and displaying associated tools - show 'toolType' - e.g. Web service, Library, etc

**Comment by knirirr** [comment]
Saving the API response has turned out to be a bit tricky due to having to pass around the JSON via forms so I have for now implemented this using the existing API calls as suggested by @njall . If that's OK then this could perhaps be closed.

**Comment by njall** [comment]
Yep, that's fine. We can think about a caching/backing-up mechanism if we start running into scalability related performance issues

**Comment by knirirr** [comment]
Thanks. If we do go that route then perhaps sending the api response to a local route via AJAX so it could be stored would be the way to go, rather than using forms.
