### ISSUE TITLE
Background job/logic for running event feeds

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#43]
This needs to be thought through and once decided - needs documenting

**Comment by knirirr** [comment]
The scrapers are currently such that they will update a resource if it exists or create it if it doesn't. So, a very simple option would be to run a cron job which activates the relevant rvm gemset and then runs the scripts, logging that it has done so. If we were to do this then the script and crontab entry should be added to the scraper repository.

Or, there seem to be various gems for running scheduled jobs:

https://www.ruby-toolbox.com/categories/scheduling

This one, for example, simply creates a cron entry for the appropriate tasks:

https://github.com/javan/whenever

Others are fancier (I see that there's a Resque one), but do we need anything that fancy when a daily scrape via cron would do the trick? What do you think?

**Comment by knirirr** [comment]
I created a cron job for this some time ago - it seems to have been running but not everything is updating successfully, so I will investigate.

**Comment by knirirr** [comment]
Seems to be working for the moment but we ought to keep an eye on it and update as new scrapers become available.

**Comment by anenadic** [comment]
Is this definitely working on TeSS production and can we close this issue?
