### ISSUE TITLE
Internal server error when editing record

### ISSUE THREAD

**Issue by knirirr** [ElixirUK/TeSS#446]
After creating a record I went back to edit it and got an internal server error. According to the logs it's:

    Errno::ECONNREFUSED (Connection refused - connect(2) for "bio.tools" port 443): app/controllers/materials_controller.rb:38:in `edit'

...so, presumably exceptions should be caught for the [relevant line](https://github.com/ElixirUK/TeSS/blob/master/app/controllers/materials_controller.rb#L38)

**Comment by fbacall** [comment]
I'll just delete that code because it doesn't seem to do anything anyway
