### ISSUE TITLE
Weird text overflow issue

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#448]
On the title and URL here:
https://tess.elixir-europe.org/materials/who-is-doing-what-on-the-cheese-surface-overview-of-the-cheese-microbial-ecosystem-functioning-by-metatranscriptomic-analyses-55c4b5d0-ba6e-4ae0-879f-7bc27c10b3eb

**Comment by knirirr** [comment]
It's caused by the long URL - I'll see if I can find some means of persuading it to wrap.
