### ISSUE TITLE
Put the cookie disclaimer/warning 

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#49]

**Comment by fbacall** [comment]
Not needed, see:
http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm#section_2

> Cookies clearly exempt from consent according to the EU advisory body on data protection- WP29pdf include:

>  * user‑input cookies (session-id) such as first‑party cookies to keep track of the user's input when filling online forms, shopping carts, etc., for the duration of a session or persistent cookies limited to a few hours in some cases
>  * authentication cookies, to identify the user once he has logged in, for the duration of a session
    user‑centric security cookies, used to detect authentication abuses, for a limited persistent duration
