### ISSUE TITLE
Add a feed for events (courses) from Swedish SciLifeLab

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#58]
There is an RSS feed at:
https://www.scilifelab.se/education/courses/

**Comment by knirirr** [comment]
It's empty so far for 2016:

https://www.scilifelab.se/education/courses/feed/

I can't get an RSS feed for 2015 so I'll have to come back to this one when the data are available.

**Comment by knirirr** [comment]
Sorry, this got overlooked. It seems as if they never got the RSS feed working but the HTML seemed easy enough to parse.
