### ISSUE TITLE
Add feeds for materials and events from VIB Belgium

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#59]
Training materials from: 
https://www.bits.vib.be/training, 

and course events from: 
http://www.vib.be/en/training/Pages/Training-Categories.aspx

**Comment by knirirr** [comment]
Materials added: https://github.com/ElixirUK/newtessscraper/commit/6f1e377c042d8a6eb53390cdee5829c14eb81bed

**Comment by knirirr** [comment]
Materials were pretty bad but events are worse. Does anyone know what the chance is that they might be willing to provide API access?
