### ISSUE TITLE
Compile a list fo previously entered keywords and offer them as autocomplete for keywords

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#67]

**Comment by njall** [comment]
Implementation ideas:
1. Have an :after_save method to add the keyword to a file containing a list of previous keywords; if it isn't already in there. 
2. Have a nightly job that gets all keywords (e.g. %(Material Package ContentProvider).each{|model| model.constantize.all.collect{|m| m.keywords}}) and compiles them into a file. 
3. Tween the attribtue keyword from being a part of a model by replacing it for the annotation engine so we can do realtime queries of all keywords.

**Comment by njall** [comment]
1. is quick and easy but has no weighting on frequency which we might want - doesn't account for deletion.
2. Will not provide uptodate keyword lists. Maybe could be used in tandem with 1.
3. is a lot more difficult; maybe it could be implemented later.

**Comment by knirirr** [comment]
Take a look at the license field here:

https://biosharing.org/advanced-search/?search_state=visible

To make that work I use this API:

https://biosharing.org/content/autocomplete/licenses/unique

All that does is grab all the license fields from the database, remove duplicates and serve up in the JSON format the autocomplete requires. Some javascript then handles the autocomplete.
