### ISSUE TITLE
/users/new causes the following notice: 'Sorry, that profile couldn't be found.' 

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#68]
/users/new causes the following notice: 'Sorry, that profile couldn't be found.' We either should not allow the 'New' button on the users index page or should only allow it for admins and in addition the notice seems wrong in this case - should be an error saying 'You are no allowed to see that page'. 

We also need some tests so we can more easily detect issues like this.

**Comment by knirirr** [comment]
I've restricted access to users to the admin only - users should be handling their accounts via the Devise sign up pages anyway.
