### ISSUE TITLE
Investigate and implement a versioning Gem

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#7]
To override normal save functionality with a gem that creates a new version everytime an update is made. This should allow us to fallback if something is incorrect

**Comment by knirirr** [comment]
It looks like paper_trail will do the trick and it also integrates with rails_admin. When installing, note the instructions here:

https://github.com/sferik/rails_admin/wiki/Papertrail

**Comment by knirirr** [comment]
If paper_trail is acceptable, could this be closed?
