### ISSUE TITLE
Empty text for Event Providers

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#71]
The iann uploader is sending empty strings for providers that are missing. Either the scraper shouldn't and/or the controller shouldn't accept them. To illustrate the error; run Event.all.collect{|x| x.provider} in console. The output is approx:

[...idge Healthtech Institute", "", "New York Academy of Sciences", "SIB", "", "SIB", "", "", "", "", "", "Cambridge Healthtech Institute", "", "Cambridge Healthtech Institute", "", "", "", "", "", "GTPB", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "CSH", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "EMBO", "", "SIB", "EMBO", "", "", "EMBO", "EMBO", "EMBO", "EMBO", "EMBO", "EMBO", "EMBO", "EMBO", "", "EMBO", "GTPB", "Wellcome Trust ", "", "", "", "", "SIB", "", "", "", "", "", "", "", "SIB", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "GTPB", "", "", "", "", "", "", "", "", "", "", "", "", "", "GTPB", "", "", "", "", "", "", "", "", "", "SIB", "GTPB", "", "", "", "", "CHI", "", "", "GTPB", "", "TGAC", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "TGAC", "tgac", "", "", "", "", "", "EMBL", "", "", "", "", "", "", "", "EMBL", "", "GTPB", "", "SIB", "", "", "", "", "", "", "", "", "", "tgac", "tgac", "tgac", "tgac", "tgac", "tgac", "TGAC", "tgac", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Pacific Symposium on Biocomputing"]

**Comment by knirirr** [comment]
I've fixed this by modifying the models such that a content_provider has_many events and event belongs_to content_provider. There's still a content_provider string field which could be left in or removed. Updates have been made to the scrapers as well.

This update will involve a database migration.
