### ISSUE TITLE
Add a feed for materials and events (courses) from the Dutch node

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#72]
Create event scraper for  http://www.dtls.nl/courses/
Celia to confirm if there is an XML export or API to the calendar related to the above DTL's course page
Celia to confirm if course events from DTL (http://www.dtls.nl/courses/) contain the same events or are a superset of events from BioSB (http://biosb.nl/education/course-portfolio-2/ and http://biosb.nl/events/)

**Comment by knirirr** [comment]
Has there been any response from Celia on this issue?
