### ISSUE TITLE
Goblet scraper needs updating - it now has 4 pages of resources

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#73]
At the moment it only looks for pages 0,1,2 but there is now page 3 as well. There is of course no way to discover how many pages there are, apart from going up the page number and then finding the page that says 'There are not training materials or course pages categorised with this term.', e.g. page:

http://www.mygoblet.org/training-portal?page=4

**Comment by knirirr** [comment]
That Goblet scraper is deprecated - we can now use the Goblet API scraper:

https://github.com/ElixirUK/newtessscraper/blob/master/goblet_api_scraper.rb

**Comment by knirirr** [comment]
https://github.com/ElixirUK/newtessscraper/commit/777e6216451afb04dccd42612ee13fd33691aa96
