### ISSUE TITLE
Some filter values/resouce descriptors coming from scrapers are empty strings

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#74]
Some filter values/resource descriptors coming from scrapers are empty strings - and they appear empty on the faced sidebar (on both materials and events). 
![screen shot 2016-01-29 at 09 24 51](https://cloud.githubusercontent.com/assets/631719/12671840/2e930a6c-c66a-11e5-9adf-0e326feff6c8.png)

**Comment by njall** [comment]
Same as #71

**Comment by knirirr** [comment]
I've purged and recreated my local database, then re-loaded data via the existing scrapers. There's no sign of any missing elements in the sidebar. Are either of you able to replicate this problem on your own installation?

**Comment by njall** [comment]
I've blocked any empty filters in the UI so it shouldn't be an issue if it is saving empty strings or not
