### ISSUE TITLE
Disallow creation of new events in TeSS

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#76]
Block the route and also remove the button from the UI

**Comment by knirirr** [comment]
Should admins have access to these features? If so then the same code I used to secure users could be applied to events.

**Comment by knirirr** [comment]
I've assumed that the answer is yes and hidden those routes to non-admins. The button already seems to be missing on the events index page.

**Comment by anenadic** [comment]
These routes should be forbidden to non-admins too, basically we do not want to allow manual creation/modification of events at all. Just via the API (there simply is no use case for manual addition of events). So, /events/new and /events/:id/new should produce an error message in the UI, but when accessed via the API (SML or JSON) they should respond as they are doing now.

**Comment by anenadic** [comment]
I had a look into this and Stackoverflow has some answers, e.g.: http://stackoverflow.com/questions/4997788/rails-3-restricting-formats-for-action-in-resource-routes

**Comment by knirirr** [comment]
We'll still be able to create any object via /admin, of course.

**Comment by knirirr** [comment]
This seems to work best by using a before_action on the offending routes to redirect to /events. I'll need to fix some tests then I'll commit the changes.
