### ISSUE TITLE
Many material descriptions have 'added automatically' string appended to description - possibly a log line from scrapers

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#86]
This string appendix needs to be removed.

**Comment by knirirr** [comment]
I put that line there on purpose - what's wrong with it?

**Comment by anenadic** [comment]
The string needs to be removed, all/most of materials are added automatically so no need to point this out. Also, we need to make more effort into extracting description and not use the title as description with appended 'added automatically' string, for e.g. GOBLET scraper.

**Comment by knirirr** [comment]
What do you suggest I add in those cases where no description is readily available (due to lack of API or description). Should that field simply be left blank? I put that string in so that there was at least something there.

**Comment by anenadic** [comment]
We can contact GOBLET representatives (will mention it to Terri later today) to provide more fields in GOBLET's API. In the meantime, we have to fall back to scraping their HTML pages which contain title, description, scientific topics, keywords and target audience and include that information in TeSS.
