### ISSUE TITLE
Add functionality to search page

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#89]
Add filtering for each of the tabs 
Search results for user matches too

**Comment by anenadic** [comment]
Need pagination for large number of results.

**Comment by njall** [comment]
Going to put a hack in for a placeholder because of the Alpha release at all hands. 

Instead of having all that pagination and filtering within the search index page - Going to put a link for each result model-type to recreate the search in that model. e.g on the search results for NGS, the  events tab will have a 'see more results' button with tessurl.org/events?q=NGS(&page=2)  - Not sure about pagination bit though
