### ISSUE TITLE
Venue has full address on events

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#98]
Field 'venue' for events has a very long value - sometimes a full paragraph of text coming from iAnn. We either need to see if we can parse our something meaningful out  if or just simply truncate to a certain sensible number of characters.
![screen shot 2016-02-09 at 09 44 23](https://cloud.githubusercontent.com/assets/631719/12912676/034b1560-cf12-11e5-8ea7-960bf8cb2d3e.png)

**Comment by knirirr** [comment]
I've tried the following:

- Truncating the display.
- Trimming out certain common strings (e.g. "The event is organised at...") from some scrapers.

There's some scope for using the Ruby Geocoder to pull some information out, e.g. I have got coordinates for some events based on the venue field where scraping them isn't possible.
